### ISSUE TITLE
При обновлении не работают ревью с русскими символами...

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/manabot#101]
Traceback (most recent call last):
  File "./manabot", line 20, in <module>
    app.run()
  File "/home/dron/Projects/manabot/tb/application.py", line 120, in run
    self.storage.save(a)
  File "/home/dron/Projects/manabot/tb/storage/utility.py", line 7, in save
    storage.save(action)
  File "/home/dron/Projects/manabot/tb/storage/database.py", line 6, in save
    action.save(self.db)
  File "/home/dron/Projects/manabot/tb/sources/gerrit.py", line 115, in save
    self.review['subject']
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-31: ordinal not in range(128)

**Comment by DronMDF** [comment]
https://py.checkio.org/forum/post/1766/unicode-in-python/
Можно решить через переменную окружения.
Но не понятно, почему нельзя было использовать системный язык?

**Comment by DronMDF** [comment]
А, ну я ж понял.
Для proxychains я же все переменные окружения сбрасываю, иначе он не работает.
Вот и локали наверное тоже слетают.
